# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
  ARM_PASS: $(adminPass)

trigger:
- none

pool:
  name: 'Home1'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: ''
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureConnection'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'DEVOPSSANDBOX'
    location: 'west europe'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)/Asp/appserviceplan.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)/Asp/appserviceplan.parameters.json'
    overrideParameters: '-appServicePlanName $(aspName)'
    deploymentMode: 'Incremental'