# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/
variables:
  - group: project-infrastructure-dev
steps:
- task: CopyFiles@2
  inputs:
     SourceFolder: ''
     Contents: '**'
     TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: AzureConnMG
    action: 'Create Or Update Resource Group'
    resourceGroupName: pythonsolution
    location: $(variables.location)
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)/acr/acr.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)/acr/acr.parameters.json'
    overrideParameters: '-acrName acrlabpython'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: AzureConnMG
    action: 'Create Or Update Resource Group'
    resourceGroupName: pythonsolution
    location: $(variables.location)
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)/akv/akv.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)/akv/akv.parameters.json'
    overrideParameters: '-vaultName akvlabpython'
    deploymentMode: 'Incremental'

- bash: az login --service-principal -u 11e1dfbe-bd42-4a67-9b8f-da271d7e323d  -p Epf8Q~tAGlcB6bihKYK4xtLB3Tl31UnS5weH5a20  --tenant c9a7654a-5212-4510-94a0-57f7f18d33b6
  displayName: 'Login into my Tenant'

- bash: az ad sp create-for-rbac --name http://$(acrName)-pull --scopes $(az acr show --name $(acrName) --query id --output tsv) --role acrpull
