# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/
variables:
  - group: project-infrastructure-dev
steps:
- task: CopyFiles@2
  inputs:
     SourceFolder: ''
     Contents: '**'
     TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: AzureConnection
    action: 'Create Or Update Resource Group'
    resourceGroupName: pythonsolution
    location: $(variables.location)
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)/acr/acr.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)/acr/acr.parameters.json'
    overrideParameters: '-acrName acrlabpython'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: AzureConnection
    action: 'Create Or Update Resource Group'
    resourceGroupName: pythonsolution
    location: $(variables.location)
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)/akv/akv.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)/akv/akv.parameters.json'
    overrideParameters: '-akvName akvlabpython'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: AzureConnection
    action: 'Create Or Update Resource Group'
    resourceGroupName: pythonsolution
    location: $(variables.location)
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)/aci/aci.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)/aci/aci.parameters.json'

