trigger: none

parameters:
   AzureService: ''
   tempName: ''
   rg: ''
   
steps:

- template: azure-pipelines.yml
  parameters:
    PaaSService: '${{parameters.azureService}}'
    templateName: '${{parameters.tempName}}'
    ResourceGroup: '$${{parameters.rg}}'
    AzureConn: 'AzureConnection'
    location: 'west europe'
