trigger: none

pool:
  name: 'Home1'

steps:

- template: azure-pipeline.yml
  parameters:
    PaaSService: 'Asp'
    templateName: 'appserviceplan'
    ResourceGroup: 'SandBoxRg'
    AzureConn: 'AzureConnection'
    location: 'west europe'