trigger: none

pool:
  name: 'Home1'

steps:

- template: azure-pipelines.yml
  parameters:
    PaaSService: 'Asp'
    templateName: 'appserviceplan'
    ResourceGroup: 'SandBoxRg'
    AzureConn: 'AzureConnection'
