trigger: none

variables:
  - azureService: 'aks'
  - tempName: 'aks'
  - rg: ''
  

steps:

- template: azure-pipelines.yml
  parameters:
    PaaSService: '$azureServices'
    templateName: '$tempName'
    ResourceGroup: '$rg'
    AzureConn: 'AzureConnection'
    location: 'west europe'
